services:
  - type: web
    name: llm_doc_processor
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
